package reciclaServer.models;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "position")
public class Position {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)

    private long id;

    private double latitude;

    private double longitude;

    public long getId() {
        return id;
    }

    public double getLatitude() {
        return latitude;
    }

    public double getLongitude() {
        return longitude;
    }
}
