package reciclaServer.models;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIdentityReference;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import reciclaServer.config.EntityIdResolver;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Timestamp;

@Entity
@Table(name = "recycle_items")
@JsonIdentityInfo(
        generator = ObjectIdGenerators.PropertyGenerator.class,
        resolver = EntityIdResolver.class,
        scope = RecycleItem.class,
        property = "id")
public class RecycleItem {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @NotNull
    private String name;

    private String image;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "recycle_user")
    @JsonIdentityReference(alwaysAsId = true)
    private User recycleUser;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "storage")
    @JsonIdentityReference(alwaysAsId = true)
    private Storage storage;

    @ManyToOne(cascade = CascadeType.ALL)
    @NotNull
    @JoinColumn(name = "item_type")
    private ItemType itemType;

    private Timestamp createdDate;

    public RecycleItem() { //Needed for JPA

    }

    public String getName() {
        return name;
    }

    public long getId() {
        return id;
    }

    public String getImage() {
        return image;
    }

    public User getRecycleUser() {
        return recycleUser;
    }

    public ItemType getItemType() {
        return itemType;
    }

    public Storage getStorage() {
        return storage;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public void setRecycleUser(User recycleUser) {
        this.recycleUser = recycleUser;
    }

    public void setStorage(Storage storage) {
        this.storage = storage;
    }

    public void setItemType(ItemType itemType) {
        this.itemType = itemType;
    }

    public Timestamp getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }
}
