package reciclaServer.models;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIdentityReference;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import reciclaServer.config.EntityIdResolver;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Timestamp;
import java.util.List;

@Entity
@Table(name = "users")
@JsonIdentityInfo(
        generator = ObjectIdGenerators.PropertyGenerator.class,
        resolver = EntityIdResolver.class,
        scope = User.class,
        property = "id")
public class User {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @NotNull
    private String email;

    private String password;

    private String username;

    private String fullName;

    private String profilePicture;

    private String accessToken;

    private Timestamp createdDate;

    @Enumerated(EnumType.STRING) //Fix: by default enums are persisted as int using oridinal
    private TypeUser type;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "last_position")
    private Position lastPosition;

    @OneToMany(mappedBy = "recycleUser")
    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
    @JsonIdentityReference(alwaysAsId = true)
    private List<RecycleItem> recycleItems;

    private int points;

    private int gamePoints;

    private Timestamp lastGameDate;

    @OneToMany(mappedBy = "user")
    private List<UserQuestion> questionsDone;


    public User() { //Needed for JPA

    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getProfilePicture() {
        return profilePicture;
    }

    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public void setRecycleItems(List<RecycleItem> recycleItems) {
        this.recycleItems = recycleItems;
    }

    public Timestamp getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }

    public List<RecycleItem> getRecycleItems() {
        return recycleItems;
    }

    public Position getLastPosition() {
        return lastPosition;
    }

    public void setLastPosition(Position lastPosition) {
        this.lastPosition = lastPosition;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public TypeUser getType() {
        return type;
    }

    public void setType(TypeUser type) {
        this.type = type;
    }

    public int getPoints() {
        return points;
    }

    public void setPoints(int points) {
        this.points = points;
    }

    public int getGamePoints() {
        return gamePoints;
    }

    public void setGamePoints(int gamePoints) {
        this.gamePoints = gamePoints;
    }

    public Timestamp getLastGameDate() {
        return lastGameDate;
    }

    public void setLastGameDate(Timestamp lastGameDate) {
        this.lastGameDate = lastGameDate;
    }

    public List<UserQuestion> getQuestionsDone() {
        return questionsDone;
    }

    public void setQuestionsDone(List<UserQuestion> questionsDone) {
        this.questionsDone = questionsDone;
    }
}
